crtmqm CHENNAIFR 
crtmqm BANGALOREFR
#crtmqm MUMBAIPR
#crtmqm NEWDELHIPR

strmqm CHENNAIFR 
strmqm BANGALOREFR

echo "ALTER QMGR REPOS(NETWORK)" | runmqsc CHENNAIFR
echo "ALTER QMGR REPOS(NETWORK)" | runmqsc BANGALOREFR

echo "DEFINE CHANNEL(TO.BANGALOREFR) CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CLUSTER(NETWORK) SSLCAUTH(OPTIONAL)" | runmqsc BANGALOREFR
echo "DEFINE CHANNEL(TO.CHENNAIFR)   CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CLUSTER(NETWORK) SSLCAUTH(OPTIONAL)" | runmqsc CHENNAIFR
#echo "DEFINE CHANNEL(TO.MUMBAIPR)   CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CLUSTER(NETWORK) SSLCAUTH(OPTIONAL)" | runmqsc MUMBAIPR
#echo "DEFINE CHANNEL(TO.NEWDELHIPR) CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CLUSTER(NETWORK) SSLCAUTH(OPTIONAL)" | runmqsc NEWDELHIPR

echo "DEFINE CHANNEL(TO.BANGALOREFR) CHLTYPE(CLUSSDR) TRPTYPE(TCP) CLUSTER(NETWORK) CONNAME('127.0.0.1(8787)')" | runmqsc CHENNAIFR
echo "DEFINE CHANNEL(TO.CHENNAIFR)   CHLTYPE(CLUSSDR) TRPTYPE(TCP) CLUSTER(NETWORK) CONNAME('127.0.0.1(7878)')" | runmqsc BANGALOREFR

echo "DEFINE QLOCAL(TESTCLUSQ) CLUSTER(NETWORK)" | runmqsc CHENNAIFR

runmqlsr -m CHENNAIFR -t TCP -p 7878 &
runmqlsr -m BANGALOREFR -t TCP -p 8787 &


