#!/sbin/sh

#
# MQ startup
#

PATH=/sbin:/usr/sbin:/usr/bin
export PATH

rval=0
set_return() {
    x=$?
    if [ $x -ne 0 ]; then
        echo "ERROR CODE $x"
        rval=1
    fi
}

case $1 in

    start_msg)
            echo "Starting MQ Manager"
            ;;

    stop_msg)
            echo "Terminating MQ Manager"
            ;;

    'start')
            if [ -f /etc/rc.config.d/mqm ] ; then
                    . /etc/rc.config.d/mqm
            else
                    echo "ERROR: /etc/rc.config.d/mqm defaults file MISSING"
            fi

            # Start All MQ Servers
            if [ "$MQM" -eq 1 ] ; then
                su - mqm -c "/var/mqm/scripts/mqmstart"
                echo return code = $?
                set_return
            fi
            ;;

    'stop')
            if [ -f /etc/rc.config.d/mqm ] ; then
                    . /etc/rc.config.d/mqm
            else
                    echo "ERROR: /etc/rc.config.d/mqm defaults file MISSING"
            fi

            # Stop All MQ Servers
            if [ "$MQM" -eq 1 ] ; then

                #ps -fe | grep mq | grep var | grep -v grep | awk '{print $(NF-1)}' | while read n
                dspmq | grep Running | cut -f2 -d'(' | cut -f1 -d')' | while read n
                do
                su - mqm -c "/usr/bin/endmqm -i $n &"
                done

                set_return
            fi
            ;;

     *)
            echo "usage: $0 {start|stop}"
            ;;
esac

exit $rval

